# Generated by Django 5.1.3 on 2024-12-06 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electro1', '0002_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
