# Generated by Django 5.1.3 on 2024-12-06 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electro1', '0003_imageprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('name', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=50)),
            ],
        ),
    ]
