# Generated by Django 5.1.3 on 2024-12-06 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electro1', '0004_teammember'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('testimonial', models.TextField()),
                ('image', models.ImageField(upload_to='images/')),
                ('name', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=50)),
            ],
        ),
    ]
