# Generated by Django 5.1.3 on 2024-12-07 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('electro1', '0008_rename_user_userprofile_customer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ImageProfile',
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
