# Generated by Django 5.1.3 on 2024-12-07 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('electro1', '0010_userprofile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='user',
            new_name='prof',
        ),
    ]
