# Generated by Django 5.1.3 on 2024-12-09 11:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electro1', '0011_rename_user_userprofile_prof'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='prof',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='electro1.user'),
        ),
    ]
