# Generated by Django 5.1.3 on 2024-12-09 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('electro1', '0014_alter_userprofile_prof'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
