# Generated by Django 5.1.3 on 2024-12-09 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('electro1', '0016_userprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
