# Generated by Django 5.1.3 on 2024-12-09 22:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('electro1', '0023_alter_customer_email_alter_customer_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='user',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='customer',
        ),
    ]
